apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    description: Enforce the mesh level strict mtls PeerAuthentication.
  name: peerauthnmeshstrictmtls
spec:
  crd:
    spec:
      names:
        kind: PeerAuthnMeshStrictMtls
      validation:
        openAPIV3Schema:
          type: object
          properties:
            rootNamespace:
              description: Istio root namespace, default value is "istio-system" if not specified.
              type: string
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |-
      package istio.security.peerauthentication

      violation[{"msg": msg}] {
        root_ns := object.get(object.get(input, "parameters", {}), "rootNamespace", "istio-system")
        not namespace_has_default_strict_mtls_pa(root_ns)
        msg := sprintf("Root namespace <%v> does not have a strict mTLS PeerAuthentication", [root_ns])
      }

      namespace_has_default_strict_mtls_pa(ns) {
        pa := data.inventory.namespace[ns][_].PeerAuthentication[_]
        pa.spec.mtls.mode == "STRICT"
      }
