apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: best-app-ever
  namespace: best-app-ever
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/mathieu-benoit/istio-gatekeeper-demos
    revision: HEAD
    branch: new-test-app-ready
    dir: best-app-ever
    auth: none
