apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: best-app-ever
  namespace: best-app-ever
subjects:
- kind: ServiceAccount
  name: ns-reconciler-best-app-ever-best-app-ever-13
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io