apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: onlineboutique
  namespace: onlineboutique
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/mathieu-benoit/istio-gatekeeper-demos
    revision: HEAD
    branch: main
    dir: onlineboutique
    auth: none