apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onlineboutique
  namespace: onlineboutique
subjects:
- kind: ServiceAccount
  name: ns-reconciler-onlineboutique-onlineboutique-14
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io