apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingress
  namespace: istio-ingress
subjects:
- kind: ServiceAccount
  name: ns-reconciler-istio-ingress-istio-ingress-13
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io