apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSidecarInjection
metadata:
  name: pod-sidecar-injection
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod
    excludedNamespaces:
    - kube-system # to exclude istio-cni pods.
