apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SidecarInjectionAnnotation
metadata:
  name: pod-sidecar-injection
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - apps
      kinds:
      - Deployment
    excludedNamespaces:
    - kube-system # to exclude istio-cni pods.
