name: ci-apps-gator
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  gator:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install gator
        run: |
          curl -OL https://github.com/open-policy-agent/gatekeeper/releases/download/v${GATOR_VERSION}/gator-v${GATOR_VERSION}-linux-amd64.tar.gz
          tar xvf gator-v${GATOR_VERSION}-linux-amd64.tar.gz && rm gator-v${GATOR_VERSION}-linux-amd64.tar.gz
        env:
          GATOR_VERSION: 3.9.0
      - name: gator verify
        run: ./gator verify test/suite.yaml
      - name: gator test
        run: |
          rm -rf test
          rm .github/workflows/*
          ./gator test -f . -o json > gator-error.json
      - name: write errors in summary
        if: ${{ failure() }}
        run: |
          echo "🚫 gator errors:" >> $GITHUB_STEP_SUMMARY
          cat gator-error.json | jq -r '.[]? | "❌ \(.constraint.metadata.name) - \(.msg)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
