name: ci-apps-kpt
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  kpt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install kpt
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v${KPT_VERSION}/kpt_linux_amd64 > kpt
          chmod +x kpt
        env:
          KPT_VERSION: 1.0.0-beta.21
      - name: gatekeeper
        run: |
          ./kpt fn eval . --image gcr.io/kpt-fn/gatekeeper:v0.2 --results-dir .
      - name: write errors in summary
        if: ${{ failure() }}
        run: |
          echo "🚫 gatekeeper errors:" >> $GITHUB_STEP_SUMMARY
          cat results.yaml | yq -r '.items[]?.results' -o json | jq -r '.[]? | "❌ \(.message)"' | sed 's/<//g;s/>//g' >> $GITHUB_STEP_SUMMARY
