name: ci-policies
on:
  push:
    branches:
      - main
    paths:
      - 'constraints/**'
      - 'constrainttemplates/**'
      - 'test/**'
  pull_request:
    paths:
      - 'constraints/**'
      - 'constrainttemplates/**'
      - 'test/**'
jobs:
  gator:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install gator
        run: |
          curl -OL https://github.com/open-policy-agent/gatekeeper/releases/download/v${GATOR_VERSION}/gator-v${GATOR_VERSION}-linux-amd64.tar.gz
          tar xvf gator-v${GATOR_VERSION}-linux-amd64.tar.gz && rm gator-v${GATOR_VERSION}-linux-amd64.tar.gz
        env:
          GATOR_VERSION: 3.10.0
      - name: gator verify
        run: ./gator verify test/suite.yaml
