name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install kpt	
        run: |
          curl -L https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.14/kpt_linux_amd64 > ./kpt
          chmod +x ./kpt
          ./kpt version
      - name: gatekeeper
        run: |
          ./kpt fn eval . --image gcr.io/kpt-fn/gatekeeper:v0.2